#!/usr/bin/env python3
import os
from pathlib import Path

from ament_index_python.packages import get_package_share_directory

workspace = Path(get_package_share_directory("orbslam3_ros2")).parents[2]
library_dirs = [
    workspace / "local" / "lib",
    workspace / "sysroot" / "opt" / "ros" / "jazzy" / "lib",
    workspace / "sysroot" / "usr" / "lib" / "x86_64-linux-gnu",
    Path("/usr/local/lib"),
]
os.environ["LD_LIBRARY_PATH"] = ":".join(map(str, library_dirs)) + ":" + os.environ.get("LD_LIBRARY_PATH", "")

config = Path(get_package_share_directory("orbslam3_ros2")) / "rviz" / "orbslam3.rviz"
os.execvp("rviz2", ["rviz2", "-d", str(config)]) 
