/dense_mapper:
  ros__parameters:
    voxel_size: 0.04
    pixel_stride: 4
    min_depth: 0.25
    max_depth: 6.0
    publish_every_n_frames: 10
    save_path: /home/h/ORBSLAM_ws/maps/latest_dense_map.ply
    autosave_seconds: 10.0
    color_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_raw
    pose_topic: /orb_slam3/pose
    camera_info_topic: /camera/color/camera_info
    tracking_state_topic: /orb_slam3/tracking_state
    imu_initialized_topic: /orb_slam3/imu_initialized
    map_frame: orb_map
