/orb_slam3/rgbd:
  ros__parameters:
    color_topic: /camera/color/image_raw
    depth_topic: /camera/depth/image_raw
    imu_topic: /camera/gyro_accel/sample
    use_imu: true
    enable_viewer: true
    map_frame: orb_map
    camera_frame: orb_camera
    max_path_poses: 10000
